language: cpp

matrix:
  include:

  - os: linux
    addons:
      apt:
        packages:
        - zlib1g-dev
        - python-dev
        - python-setuptools
        - ninja-build

  - os: osx
    osx_image: xcode11
    addons:
      homebrew:
        packages:
          - zlib
          - ninja
    before_install:
      - brew update
      - brew install zlib ninja
      - python2 -m pip install --upgrade setuptools


script:

- python2 setup.py build
- python2 setup.py bdist_wheel

- mkdir build_2
- cd build_2

- cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
- cmake --build .
- cmake --build . --target package

deploy:
  provider: releases
  api_key:
    secure: dSeWsCyU+nI4kyPxN3phsHL7FWi2e7Jy1z286BS1sTJU1Z7TbCUUpJ0bNDFJYniLPkVVJ/7a9C1Rvg+h8VRjhqXjUCSnj4kg6mExnM+FlherRTncZbhY/2wTv98x4cLnMJKK+12ngV7QNNFbqI1jPmyFe1Rc2SYgiMKIpUK2GcE8uDAcILsgfhC7Tei7QMjFSc0vx8qbZDr6vRK+XkxfHsvCYayjoeuoWT3ILYGvXBfDzrbpYuH4YNColqbi/2Cn7AHMZTT9NzToVMAPFPY4aRTxCTfcKe33Kd6jEQJoO1XDHKAaHl4l/vBo6AviRve8vdgdSAV8YGrWnumOSxmgckZvf4FU3WSDGQwhkkXU3Gr4OTcME7tNJ7lgVhC7cmMYGCF4LIPAXOJqPRH4BOLL6kGnD91URPy4E8DPbLzHHcrTeNydppo8h84JqHGQdvpA8uC4Sk7a1FMwePLtDhwHjeSJrmle59rIdXgiMbij2HFqBjtJhpNz1XQ91KlyN8F263djrYLFy7/hbhJnrZK5gUZ9eX+WRb7E4oKIzlYR+d5ndtHxQ41rnooTvo1ujQNZWKj7/SoJbGtl9T7hdCGM9TNePj6/BCHzmliPuForOqUXoF/qcx1KdNFyOb5wA5IfMNForbaUS1LFLCfrUtTflPTifpRlslkI9X0XLANDNlA=
  skip_cleanup: true
  file_glob: true
  file: 
    - pyzz_extension-*.tar.gz
    - ../dist/pyzz-*.whl
  on:
    repo: sterin/pyzz-build
    tags: true
