on: [push]

jobs:

  build:

    strategy:
      matrix:
        python-version: 
          - "2.7"
        os:
          - ubuntu-16.04
          - macos-latest
        include:
          - os: ubuntu-16.04
            python-version: "2.7"
            platform-options: "--plat-name=manylinux2014_x86_64"
          - os: macos-latest
            python-version: "2.7"
            platform-options: "--plat-name=macosx_10_14_x86_64"

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule update --init --force --recursive
    
    - name: Set up Python ${{ matrix.python-version }}
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Build
      run: |
        pip install ninja
        python setup.py build

    - name: Create package
      run: |
        pip install wheel
        python setup.py bdist_wheel ${{ matrix.platform-options }}

    - name: Publish package
      if: startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        pip install twine
        twine upload dist/*
